services:
  mongo-a:
    image: mongo:latest
    ports: ["27017:27017"]
  
  mongo-b:
    image: mongo:latest
    ports: ["27018:27017"]

  warehouse:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: analytics
    ports: ["5439:5432"]
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6371:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5